version: '3'

services:

  origin:
    build:
      context: .
      dockerfile: origin/Dockerfile
    environment:
      PORT: ${ORIGIN_PORT}
      STORAGE_DIR: "files/"
    ports:
      - "${ORIGIN_PORT}:${ORIGIN_PORT}"

  backup:
    build:
      context: .
      dockerfile: origin_backup/Dockerfile
    environment:
      PORT: ${BACKUP_PORT}
      STORAGE_DIR: "files/"
    ports:
      - "${BACKUP_PORT}:${BACKUP_PORT}"

  load_balancer:
    build:
      context: .
      dockerfile: load_balancer/Dockerfile
    environment:
        PORT: ${BALANCER_PORT}
        PROXIES: ${PROXY1_PORT},${PROXY2_PORT}
        DEFAULT_PATH: "test_file.html"
        FLASK_APP: "server.py"
    ports:
      - "${BALANCER_PORT}:${BALANCER_PORT}"

  proxy1:
    build:
      context: .
      dockerfile: proxy/Dockerfile
      args:
        CACHE_DIR: "cache/"
    environment:
        PORT: ${PROXY1_PORT}
        ORIGIN_PORT: ${ORIGIN_PORT}
        FLASK_APP: "server.py"
        CACHE_DIR: "cache/"
        TTL: 120
        BASE_LATENCY: 1
        OUT_SCALE: 1.5
        IN_SCALE: 0.5
    ports:
      - "${PROXY1_PORT}:${PROXY1_PORT}"

  proxy2:
    build:
      context: .
      dockerfile: proxy/Dockerfile
      args:
        CACHE_DIR: "cache/"
    environment:
        PORT: ${PROXY2_PORT}
        ORIGIN_PORT: ${ORIGIN_PORT}
        FLASK_APP: "server.py"
        CACHE_DIR: "cache/"
        TTL: 120
        BASE_LATENCY: 1
        OUT_SCALE: 1.5
        IN_SCALE: 0.5
    ports:
      - "${PROXY2_PORT}:${PROXY2_PORT}"
  
#copy proxy service definition to start more proxy server
