version: '3'

services:
  origin:
    build:
      context: .
      dockerfile: origin/Dockerfile
    environment:
      PORT: 8001
    ports:
      - "8001:8001"
  load_balancer:
    build:
      context: .
      dockerfile: load_balancer/Dockerfile
    environment:
        PORT: 8000
    ports:
      - "8000:8000"
  proxy1:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    environment:
        PORT: 5000
    ports:
      - "5000:5000"
  proxy2:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    environment:
        PORT: 5001
    ports:
      - "5001:5001"
  

