version: '3'

services:
  origin:
    build:
      context: .
      dockerfile: origin/Dockerfile
    environment:
      PORT: 8001
    ports:
      - "8001:8001"
  primary:
    build:
      context: .
      dockerfile: primary/Dockerfile
    environment:
        PORT: 8000
    ports:
      - "8000:8000"
  backup1:
    build:
      context: .
      dockerfile: backup/Dockerfile
    environment:
        PORT: 5000
    ports:
      - "5000:5000"
  backup2:
    build:
      context: .
      dockerfile: backup/Dockerfile
    environment:
        PORT: 5001
    ports:
      - "5001:5001"
  

