# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ops.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tops.proto\x12\x04main\"@\n\nputRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x16\n\x0esequenceNumber\x18\x03 \x01(\x05\"\x19\n\ngetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"#\n\x0freplyPutRequest\x12\x10\n\x08response\x18\x01 \x01(\t\"#\n\x0freplyGetRequest\x12\x10\n\x08response\x18\x01 \x01(\t2\x96\x01\n\x14PrimaryBackupService\x12>\n\x13putRequestOperation\x12\x10.main.putRequest\x1a\x15.main.replyPutRequest\x12>\n\x13getRequestOperation\x12\x10.main.getRequest\x1a\x15.main.replyGetRequestb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ops_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUTREQUEST._serialized_start=19
  _PUTREQUEST._serialized_end=83
  _GETREQUEST._serialized_start=85
  _GETREQUEST._serialized_end=110
  _REPLYPUTREQUEST._serialized_start=112
  _REPLYPUTREQUEST._serialized_end=147
  _REPLYGETREQUEST._serialized_start=149
  _REPLYGETREQUEST._serialized_end=184
  _PRIMARYBACKUPSERVICE._serialized_start=187
  _PRIMARYBACKUPSERVICE._serialized_end=337
# @@protoc_insertion_point(module_scope)
