# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ops_pb2 as ops__pb2


class FileServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.put = channel.stream_unary(
                '/FileServer/put',
                request_serializer=ops__pb2.Chunk.SerializeToString,
                response_deserializer=ops__pb2.Reply.FromString,
                )
        self.get = channel.unary_stream(
                '/FileServer/get',
                request_serializer=ops__pb2.Request.SerializeToString,
                response_deserializer=ops__pb2.Chunk.FromString,
                )


class FileServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def put(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'put': grpc.stream_unary_rpc_method_handler(
                    servicer.put,
                    request_deserializer=ops__pb2.Chunk.FromString,
                    response_serializer=ops__pb2.Reply.SerializeToString,
            ),
            'get': grpc.unary_stream_rpc_method_handler(
                    servicer.get,
                    request_deserializer=ops__pb2.Request.FromString,
                    response_serializer=ops__pb2.Chunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def put(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/FileServer/put',
            ops__pb2.Chunk.SerializeToString,
            ops__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileServer/get',
            ops__pb2.Request.SerializeToString,
            ops__pb2.Chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
